//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.2
//     from Assets/InputActions/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/InputActions/PlayerInputActions.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @PlayerInputActions: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""PlayerControl"",
            ""id"": ""fde7551d-d479-4384-9987-358dc31d612c"",
            ""actions"": [
                {
                    ""name"": ""PlaceObject"",
                    ""type"": ""Button"",
                    ""id"": ""1e4abcd2-d52b-4e8b-8444-30216030f2e9"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectFirstSlot"",
                    ""type"": ""Button"",
                    ""id"": ""794bdbd0-9974-4c0c-8a40-ab7395f35798"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectSecondSlot"",
                    ""type"": ""Button"",
                    ""id"": ""cc006731-fd02-442f-8c8b-67806f4e5b73"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectThirdSlot"",
                    ""type"": ""Button"",
                    ""id"": ""f0c6d81d-96ea-4f0a-8b47-5b8ea78913a9"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""IncreaseSlotIndex"",
                    ""type"": ""Button"",
                    ""id"": ""285683d3-3cfb-446c-b335-c54344cc7666"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DecreseSlotIndex"",
                    ""type"": ""Button"",
                    ""id"": ""ba17a3e9-a0b8-4efb-8762-f1c58fde110b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""4b57b605-e1dd-474c-9490-a435f4b4079e"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlaceObject"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""375f39d0-fed9-4bd9-ae1d-3660e0e3bb4b"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectFirstSlot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b2190e84-4b98-4ada-83ec-f3ce4cd21ea8"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectSecondSlot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c0cb800c-7d3a-47a4-8f82-ae68a4cd641c"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectThirdSlot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d0dd631e-c360-4c33-8770-0e53ec80cbf4"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""IncreaseSlotIndex"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1758496c-77c5-4e0f-b9a8-b07010070b08"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DecreseSlotIndex"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerControl
        m_PlayerControl = asset.FindActionMap("PlayerControl", throwIfNotFound: true);
        m_PlayerControl_PlaceObject = m_PlayerControl.FindAction("PlaceObject", throwIfNotFound: true);
        m_PlayerControl_SelectFirstSlot = m_PlayerControl.FindAction("SelectFirstSlot", throwIfNotFound: true);
        m_PlayerControl_SelectSecondSlot = m_PlayerControl.FindAction("SelectSecondSlot", throwIfNotFound: true);
        m_PlayerControl_SelectThirdSlot = m_PlayerControl.FindAction("SelectThirdSlot", throwIfNotFound: true);
        m_PlayerControl_IncreaseSlotIndex = m_PlayerControl.FindAction("IncreaseSlotIndex", throwIfNotFound: true);
        m_PlayerControl_DecreseSlotIndex = m_PlayerControl.FindAction("DecreseSlotIndex", throwIfNotFound: true);
    }

    ~@PlayerInputActions()
    {
        UnityEngine.Debug.Assert(!m_PlayerControl.enabled, "This will cause a leak and performance issues, PlayerInputActions.PlayerControl.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerControl
    private readonly InputActionMap m_PlayerControl;
    private List<IPlayerControlActions> m_PlayerControlActionsCallbackInterfaces = new List<IPlayerControlActions>();
    private readonly InputAction m_PlayerControl_PlaceObject;
    private readonly InputAction m_PlayerControl_SelectFirstSlot;
    private readonly InputAction m_PlayerControl_SelectSecondSlot;
    private readonly InputAction m_PlayerControl_SelectThirdSlot;
    private readonly InputAction m_PlayerControl_IncreaseSlotIndex;
    private readonly InputAction m_PlayerControl_DecreseSlotIndex;
    /// <summary>
    /// Provides access to input actions defined in input action map "PlayerControl".
    /// </summary>
    public struct PlayerControlActions
    {
        private @PlayerInputActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public PlayerControlActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "PlayerControl/PlaceObject".
        /// </summary>
        public InputAction @PlaceObject => m_Wrapper.m_PlayerControl_PlaceObject;
        /// <summary>
        /// Provides access to the underlying input action "PlayerControl/SelectFirstSlot".
        /// </summary>
        public InputAction @SelectFirstSlot => m_Wrapper.m_PlayerControl_SelectFirstSlot;
        /// <summary>
        /// Provides access to the underlying input action "PlayerControl/SelectSecondSlot".
        /// </summary>
        public InputAction @SelectSecondSlot => m_Wrapper.m_PlayerControl_SelectSecondSlot;
        /// <summary>
        /// Provides access to the underlying input action "PlayerControl/SelectThirdSlot".
        /// </summary>
        public InputAction @SelectThirdSlot => m_Wrapper.m_PlayerControl_SelectThirdSlot;
        /// <summary>
        /// Provides access to the underlying input action "PlayerControl/IncreaseSlotIndex".
        /// </summary>
        public InputAction @IncreaseSlotIndex => m_Wrapper.m_PlayerControl_IncreaseSlotIndex;
        /// <summary>
        /// Provides access to the underlying input action "PlayerControl/DecreseSlotIndex".
        /// </summary>
        public InputAction @DecreseSlotIndex => m_Wrapper.m_PlayerControl_DecreseSlotIndex;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_PlayerControl; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="PlayerControlActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(PlayerControlActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="PlayerControlActions" />
        public void AddCallbacks(IPlayerControlActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerControlActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerControlActionsCallbackInterfaces.Add(instance);
            @PlaceObject.started += instance.OnPlaceObject;
            @PlaceObject.performed += instance.OnPlaceObject;
            @PlaceObject.canceled += instance.OnPlaceObject;
            @SelectFirstSlot.started += instance.OnSelectFirstSlot;
            @SelectFirstSlot.performed += instance.OnSelectFirstSlot;
            @SelectFirstSlot.canceled += instance.OnSelectFirstSlot;
            @SelectSecondSlot.started += instance.OnSelectSecondSlot;
            @SelectSecondSlot.performed += instance.OnSelectSecondSlot;
            @SelectSecondSlot.canceled += instance.OnSelectSecondSlot;
            @SelectThirdSlot.started += instance.OnSelectThirdSlot;
            @SelectThirdSlot.performed += instance.OnSelectThirdSlot;
            @SelectThirdSlot.canceled += instance.OnSelectThirdSlot;
            @IncreaseSlotIndex.started += instance.OnIncreaseSlotIndex;
            @IncreaseSlotIndex.performed += instance.OnIncreaseSlotIndex;
            @IncreaseSlotIndex.canceled += instance.OnIncreaseSlotIndex;
            @DecreseSlotIndex.started += instance.OnDecreseSlotIndex;
            @DecreseSlotIndex.performed += instance.OnDecreseSlotIndex;
            @DecreseSlotIndex.canceled += instance.OnDecreseSlotIndex;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="PlayerControlActions" />
        private void UnregisterCallbacks(IPlayerControlActions instance)
        {
            @PlaceObject.started -= instance.OnPlaceObject;
            @PlaceObject.performed -= instance.OnPlaceObject;
            @PlaceObject.canceled -= instance.OnPlaceObject;
            @SelectFirstSlot.started -= instance.OnSelectFirstSlot;
            @SelectFirstSlot.performed -= instance.OnSelectFirstSlot;
            @SelectFirstSlot.canceled -= instance.OnSelectFirstSlot;
            @SelectSecondSlot.started -= instance.OnSelectSecondSlot;
            @SelectSecondSlot.performed -= instance.OnSelectSecondSlot;
            @SelectSecondSlot.canceled -= instance.OnSelectSecondSlot;
            @SelectThirdSlot.started -= instance.OnSelectThirdSlot;
            @SelectThirdSlot.performed -= instance.OnSelectThirdSlot;
            @SelectThirdSlot.canceled -= instance.OnSelectThirdSlot;
            @IncreaseSlotIndex.started -= instance.OnIncreaseSlotIndex;
            @IncreaseSlotIndex.performed -= instance.OnIncreaseSlotIndex;
            @IncreaseSlotIndex.canceled -= instance.OnIncreaseSlotIndex;
            @DecreseSlotIndex.started -= instance.OnDecreseSlotIndex;
            @DecreseSlotIndex.performed -= instance.OnDecreseSlotIndex;
            @DecreseSlotIndex.canceled -= instance.OnDecreseSlotIndex;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="PlayerControlActions.UnregisterCallbacks(IPlayerControlActions)" />.
        /// </summary>
        /// <seealso cref="PlayerControlActions.UnregisterCallbacks(IPlayerControlActions)" />
        public void RemoveCallbacks(IPlayerControlActions instance)
        {
            if (m_Wrapper.m_PlayerControlActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="PlayerControlActions.AddCallbacks(IPlayerControlActions)" />
        /// <seealso cref="PlayerControlActions.RemoveCallbacks(IPlayerControlActions)" />
        /// <seealso cref="PlayerControlActions.UnregisterCallbacks(IPlayerControlActions)" />
        public void SetCallbacks(IPlayerControlActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerControlActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerControlActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="PlayerControlActions" /> instance referencing this action map.
    /// </summary>
    public PlayerControlActions @PlayerControl => new PlayerControlActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "PlayerControl" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="PlayerControlActions.AddCallbacks(IPlayerControlActions)" />
    /// <seealso cref="PlayerControlActions.RemoveCallbacks(IPlayerControlActions)" />
    public interface IPlayerControlActions
    {
        /// <summary>
        /// Method invoked when associated input action "PlaceObject" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPlaceObject(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SelectFirstSlot" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSelectFirstSlot(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SelectSecondSlot" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSelectSecondSlot(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SelectThirdSlot" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSelectThirdSlot(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "IncreaseSlotIndex" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnIncreaseSlotIndex(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "DecreseSlotIndex" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDecreseSlotIndex(InputAction.CallbackContext context);
    }
}
